# Generated by Django 4.2.8 on 2024-02-17 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('cast_name_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('cast_role_english', models.CharField(blank=True, max_length=255, null=True)),
                ('cast_role_arabic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('crew_name_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('crew_role_english', models.CharField(blank=True, max_length=255, null=True)),
                ('crew_role_arabic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movienain', models.CharField(blank=True, max_length=255, null=True)),
                ('movienaar', models.CharField(blank=True, max_length=255, null=True)),
                ('redate', models.DateField(blank=True, max_length=15, null=True)),
                ('tedate', models.DateField(blank=True, max_length=15, null=True)),
                ('mduration', models.CharField(blank=True, max_length=255, null=True)),
                ('mdiscription', models.CharField(blank=True, max_length=255, null=True)),
                ('mdiscriptionar', models.CharField(blank=True, max_length=255, null=True)),
                ('Rating', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer', models.CharField(blank=True, max_length=255, null=True)),
                ('casts', models.ManyToManyField(related_name='movies', to='movies.cast')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
                ('crews', models.ManyToManyField(related_name='movies', to='movies.crew')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.format')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.language')),
            ],
        ),
    ]
